/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class personal_nfl_protect__shell_util_AESUtil */

#ifndef Included_personal_nfl_protect_shell_util_AESUtil
#define Included_personal_nfl_protect_shell_util_AESUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     personal_nfl_protect_shell_util_AESUtil
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_personal_nfl_protect_shell_util_AESUtil_encrypt(JNIEnv *env, jclass clazz, jbyteArray data);

/*
 * Class:     personal_nfl_protect_shell_util_AESUtil
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_personal_nfl_protect_shell_util_AESUtil_decrypt(JNIEnv *env, jclass clazz, jbyteArray data);

#ifdef __cplusplus
}
#endif
#endif
